=head1 begin/end test

This tests the handling of =begin ... =end blocks

=begin codeblocks

This is a code block because it's in a =begin ... =end block whose name
does not begin with ':'

    This is also part of the code block
    
    POD command I<are not> valid here.  This is raw text.

This is more of the raw text.  This is not pod

=end codeblocks

This is a regular paragraph
