This is pre-amble

=head1 Badger::Pod::Parser Tests

This is a test document for the Badger::Pod::Parser tests in t/pod/parser.t.

    This is some verbatim text
    This is the next line

    This is the next block of verbatim text.
    There is a blank line before it.
    
    This is the third block of verbatim text.
    There are four spaces on the line above it.

This is another normal paragraph.

